import { MissionLogEntry, Message, CharacterId } from '../types';
import { CHARACTERS } from '../constants';

/**
 * ミッションをアーカイブに保存
 * @param logs 既存のログ配列
 * @param newLog 追加するログ
 * @returns 更新されたログ配列
 */
export const saveMissionToArchive = (
  logs: MissionLogEntry[],
  newLog: MissionLogEntry
): MissionLogEntry[] => {
  // 既存の同じ日＋キャラのログがあれば上書き、なければ追加
  const existingIndex = logs.findIndex(
    log => log.day === newLog.day && log.characterId === newLog.characterId
  );

  if (existingIndex >= 0) {
    const updatedLogs = [...logs];
    updatedLogs[existingIndex] = newLog;
    return updatedLogs;
  }

  return [...logs, newLog];
};

/**
 * IDでミッションを取得
 */
export const getMissionById = (
  logs: MissionLogEntry[],
  id: string
): MissionLogEntry | undefined => {
  return logs.find(log => log.id === id);
};

/**
 * フィルタリングしたミッションを取得
 */
export const filterMissions = (
  logs: MissionLogEntry[],
  filters: {
    characterId?: CharacterId;
    day?: number;
    isSpecial?: boolean;
    isSeasonal?: boolean;
    minDay?: number;
    maxDay?: number;
  }
): MissionLogEntry[] => {
  return logs.filter(log => {
    if (filters.characterId && log.characterId !== filters.characterId) return false;
    if (filters.day && log.day !== filters.day) return false;
    if (filters.isSpecial !== undefined && log.isSpecial !== filters.isSpecial) return false;
    if (filters.isSeasonal !== undefined && log.isSeasonal !== filters.isSeasonal) return false;
    if (filters.minDay && log.day < filters.minDay) return false;
    if (filters.maxDay && log.day > filters.maxDay) return false;
    return true;
  });
};

/**
 * ミッションをMarkdown形式でエクスポート
 */
export const exportMissionAsMarkdown = (log: MissionLogEntry): string => {
  const char = CHARACTERS[log.characterId];
  const charName = char?.name || log.characterId;

  let md = `# ${log.title}\n\n`;
  md += `**Day ${log.day}** | **Handler: ${charName}**\n`;
  md += `**Completed:** ${new Date(log.completedAt).toLocaleString('ja-JP')}\n\n`;

  if (log.description) {
    md += `## Description\n\n${log.description}\n\n`;
  }

  if (log.isSpecial) md += `> 🏆 **Special Mission**\n\n`;
  if (log.isSeasonal) md += `> 🎄 **Seasonal Event**\n\n`;

  if (log.messages && log.messages.length > 0) {
    md += `## Conversation\n\n`;
    log.messages.forEach(msg => {
      const time = new Date(msg.timestamp).toLocaleTimeString('ja-JP');
      if (msg.sender === 'user') {
        md += `### 👤 User (${time})\n${msg.text}\n\n`;
      } else {
        md += `### 🤖 ${charName} (${time})\n${msg.text}\n\n`;
      }
    });
  }

  md += `---\n\n`;
  md += `*Generated by CLOVER PROTOCOL*\n`;

  return md;
};

/**
 * 全ミッションをMarkdown形式でエクスポート
 */
export const exportAllMissionsAsMarkdown = (logs: MissionLogEntry[]): string => {
  let md = `# CLOVER PROTOCOL - Mission Archive\n\n`;
  md += `*Exported: ${new Date().toLocaleString('ja-JP')}*\n\n`;
  md += `---\n\n`;

  // 日付順にソート
  const sortedLogs = [...logs].sort((a, b) => b.completedAt - a.completedAt);

  sortedLogs.forEach(log => {
    md += exportMissionAsMarkdown(log);
  });

  return md;
};

/**
 * ミッションを削除
 */
export const deleteMission = (
  logs: MissionLogEntry[],
  id: string
): MissionLogEntry[] => {
  return logs.filter(log => log.id !== id);
};

/**
 * 日付別にグループ化
 */
export const groupByDate = (logs: MissionLogEntry[]): Record<string, MissionLogEntry[]> => {
  return logs.reduce((acc, log) => {
    const dateStr = new Date(log.completedAt).toLocaleDateString('ja-JP');
    if (!acc[dateStr]) acc[dateStr] = [];
    acc[dateStr].push(log);
    return acc;
  }, {} as Record<string, MissionLogEntry[]>);
};

/**
 * 統計情報を取得
 */
export const getArchiveStats = (logs: MissionLogEntry[]) => {
  const stats = {
    total: logs.length,
    special: logs.filter(l => l.isSpecial).length,
    seasonal: logs.filter(l => l.isSeasonal).length,
    byCharacter: {} as Record<CharacterId, number>,
    avgPerDay: 0,
  };

  // キャラクター別
  Object.values(CharacterId).forEach(id => {
    stats.byCharacter[id] = logs.filter(l => l.characterId === id).length;
  });

  // 1日あたりの平均
  if (logs.length > 0) {
    const days = new Set(logs.map(l => l.day)).size;
    stats.avgPerDay = Math.round((logs.length / days) * 10) / 10;
  }

  return stats;
};
